name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      - name: Install dependencies
        run: |
          pip install -r ./doc/requirements.txt
          sudo apt-get update -qy
          # pandoc is needed by nbsphinx for notebook -> RST conversion.
          sudo apt-get install -y pandoc
      - name: Sphinx build
        run: |
          cd doc
          make clean
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html/
          force_orphan: true
